name: deepguardian
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - numpy=1.24
  - pandas=1.5
  - opencv=4.7
  - scikit-learn=1.2
  - matplotlib=3.7
  - tqdm=4.65
  - streamlit=1.22
  - grad-cam=1.4
  - retina-face=0.0.14
  - pip=23.0
  - pip:
      - albumentations==1.3
      - pytorch-lightning==2.0.2
      - efficientnet-pytorch==0.7.1